/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DemoBlock: typeof import('./src/components/DemoBlock.vue')['default']
    GlobalLoading: typeof import('./src/components/GlobalLoading.vue')['default']
    GlobalMessage: typeof import('./src/components/GlobalMessage.vue')['default']
    GlobalToast: typeof import('./src/components/GlobalToast.vue')['default']
    PrivacyPopup: typeof import('./src/components/PrivacyPopup.vue')['default']
  }
}
